# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 266baf2d4661cc21cd5557767a4176fe33b892395cac29e62ae388d617fc66866d057fdbcd9dbbc7f18712688ca357e9e7e5effeed30147246662a3f465f73fb

test:
  secret_key_base: e31aa448d638028ddfe875e34ed25f8bc0a6a58f5596ef4b4278bd0ce7a7b8301e08bb6c72389977e7116d946294f42d98bcc67b9a8c3d622f3d5aeb0c805295

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
